### ISSUE TITLE
Midi out buffer growing 

### ISSUE THREAD

**Issue by romix123** [raspy135/serialmidi#10]
Hi, Thanks for your wonderful script.
I am running into problems though. I have an Arduino Nano spilling out Mido cc codes over serial using this function:
void controlChange(unsigned char channel, unsigned char control, unsigned char value) {
  Serial.write(191); //0xB0);// || channel);
  Serial.write(control);
  Serial.write(value);
}
As you can see, it is now tied to channel 16. If I do 
Serial.write(0xB0 || channel) to incorporate the actual channel I want to use, serimidi does not recognize the command at all.
Second issue, the buffer keeps growing with each command I send it.

DEBUG:root:[191, 120, 96]
DEBUG:root:[191, 120, 96, 191]
DEBUG:root:[191, 120, 96, 191, 121]
DEBUG:root:[191, 120, 96, 191, 121, 52]
DEBUG:root:[191, 120, 96, 191, 121, 52, 191]
DEBUG:root:[191, 120, 96, 191, 121, 52, 191, 122]
DEBUG:root:[191, 120, 96, 191, 121, 52, 191, 122, 41]

My Python sucks.
Is there anything I am doing wrong? I would really like to use your module.

**Comment by raspy135** [comment]
I'm not sure but I think '||' should be '|'.

**Comment by romix123** [comment]
You are (probably) correct, but that is one of the two problems. 
|| is logical boolean or (in tests), | is bitwise or.

Thanks

**Comment by raspy135** [comment]
That was a bug when I add --string option. It's fixed.
