### ISSUE TITLE
Beginner guide for Arduino Uno?

### ISSUE THREAD

**Issue by epleaner** [raspy135/serialmidi#4]
Hi! Thanks for putting this script together. I'm trying to use it to send some MIDI from my Arduino Uno to Ableton Live on Macos 11.6. I followed this tutorial: https://www.arduino.cc/en/Tutorial/BuiltInExamples/Midi and am seeing MIDI notes being sent over serial in the Arduino IDE. I am running this script using `python3 serialmidi.py --serial_name=serialmidi.py --serial_name=/dev/cu.usbmodem11301 --midi_in_name='IAC Driver Bus 1' --midi_out_name='IAC Driver Bus 1' --debug` and the script seems to be running fine. However, I am seeing no MIDI output via the script. 

Furthermore, how would I go about then setting up Ableton to see this MIDI "device" as MIDI in?

Thank you!

**Comment by raspy135** [comment]
I forgot the detail of the script, but did you create IAC Driver ? https://help.ableton.com/hc/en-us/articles/209774225-Setting-up-a-virtual-MIDI-bus

**Comment by epleaner** [comment]
Thanks @raspy135 for the reply. Yep, I have the IAC driver setup, and see the Midi Bus available in Ableton. I'm just not seeing any notes showing up as the script is running (neither in Terminal nor elsewhere).

**Comment by raspy135** [comment]
Are you seeing any debug messages when you send MIDI messages from your Arduino?
I will try the script sometime soon when I have time.

**Comment by epleaner** [comment]
Just a whole lot of:

```DEBUG:root:[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]```

**Comment by raspy135** [comment]
I see, you should see real MIDI messages in the debug messages.
If you don't modify any of Arduino example, then the baud rate is wrong.
SerialMIDI's default baud rate is 115200. You should match the baud rate.

**Comment by raspy135** [comment]
Have you solved your issue?

**Comment by epleaner** [comment]
I did not, I ended up moving to midibus via Processing to handle MIDI.

At this point I have Ableton recognizing MIDI notes coming in, but unfortunately these incoming notes are not triggering any keys being pressed on the MIDI instrument I have armed. 

But this is a separate issue.
