### ISSUE TITLE
Transfers a single note only 

### ISSUE THREAD

**Issue by bindele** [raspy135/serialmidi#6]
Hello,
the program seems to work (I can listen a single note in Ableton) but then it gives an error and stop working.

I run with this:
python3 serialmidi.py --serial_name=/dev/cu.usbserial-110 --baud=115200 --midi_in_name="Driver IAC" --midi_out_name="Driver IAC" --debug
(the parameters seems correct since it works for an initial single note)
and the output is this:

INFO:root:IN : 'Driver IAC Bus 1'
INFO:root:OUT : 'Driver IAC Bus 1'
INFO:root:Hit ctrl-c to exit
DEBUG:root:[144, 76, 1]
DEBUG:root:[144, 76, 1]
DEBUG:root:[128, 76, 1]
DEBUG:root:[128, 76, 1]
DEBUG:root:[67, 111, 109, 112, 117, 116, 101, 100, 58, 49, 53, 51, 44, 83, 101, 110, 115, 105, 116, 105, 118, 105, 116, 121, 58, 48, 44, 80, 105, 116, 99, 104, 58, 54, 51, 44, 86, 101, 108, 111, 99, 105, 116, 121, 58, 49, 44, 68, 101, 108, 97, 121, 58, 51, 48, 49, 44, 83, 117, 115, 116, 97, 105, 110, 58, 50, 48, 56, 13, 10, 144, 69, 1, 128, 69, 1, 67, 111, 109, 112, 117, 116, 101, 100, 58, 56, 48, 44, 83, 101, 110, 115, 105, 116, 105, 118, 105, 116, 121, 58]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "serialmidi.py", line 158, in midi_watcher
    midiout.send_message(message)
  File "src/_rtmidi.pyx", line 1103, in rtmidi._rtmidi.MidiOut.send_message
ValueError: 'message' longer than 3 bytes but does not start with 0xF0.
DEBUG:root:[48, 44, 80, 105, 116, 99, 104, 58, 54, 51, 44, 86, 101, 108, 111, 99, 105, 116, 121, 58, 49, 44, 68, 101, 108, 97, 121, 58, 51, 48, 49, 44, 83, 117, 115, 116, 97, 105, 110, 58, 50, 48, 56, 13, 10, 144, 69, 1, 128, 69, 1, 67, 111, 109, 112, 117, 116, 101, 100, 58, 55, 55, 44, 83, 101, 110, 115, 105, 116, 105, 118, 105, 116, 121, 58, 48, 44, 80, 105, 116, 99, 104, 58, 54, 51, 44, 86, 101, 108, 111, 99, 105, 116, 121, 58, 49, 44, 68, 101, 108]
DEBUG:root:[97, 121, 58, 51, 48, 49, 44, 83, 117, 115, 116, 97, 105, 110, 58, 50, 49, 48, 13, 10, 144, 69, 1, 128, 69, 1, 67, 111, 109, 112, 117, 116, 101, 100, 58, 55, 53, 44, 83, 101, 110, 115, 105, 116, 105, 118, 105, 116, 121, 58, 48, 44, 80, 105, 116, 99, 104, 58, 54, 51, 44, 86, 101, 108, 111, 99, 105, 116, 121, 58, 49, 44, 68, 101, 108, 97, 121, 58, 51, 48, 49, 44, 83, 117, 115, 116, 97, 105, 110, 58, 50, 49, 48, 13, 10, 144, 70, 1, 128, 70]
[SAME OUTPUT REPEATED (DEBUG:root:[97, 121, 58, 51, 48, 49...)]
^CTerminating.

I pressed CTRL+C after a while since it stopped to work.

PS. I use Arduino nano and hairless midi-serial (for windows) and It works correctly so the signal from the hardware must be correct.

**Comment by bindele** [comment]
Solved, I printed some stuff on the serial port that hairless midi serial was able to filter out but serialmidi.py not. Removed the extra output started working

**Comment by raspy135** [comment]
Hi,
Also probably you want to use different IAC Bus for Input and Output to avoid MIDI message flood?

**Comment by raspy135** [comment]
I'm closing this issue
