### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Sebastian4456** [raspy135/serialmidi#7]
New to all of this. Tried running serialmidi.py -h and this happened
![Screen Shot 2022-11-28 at 12 57 20 PM](https://user-images.githubusercontent.com/119354228/204358338-f2fc4dfd-afe3-48f4-9161-64edf10c3029.png)

**Comment by raspy135** [comment]
You need to install rtmidi. 
> pip install python-rtmidi
https://github.com/raspy135/serialmidi#requirements--installation
