### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by guilhermeollopes** [raspy135/serialmidi#9]
INFO:root:IN : ''                                                                                                                                            INFO:root:OUT : ''                                                                                                                                           INFO:root:Hit ctrl-c to exit                                                                                                                                 MIDI IN Device name is incorrect. Please use listed device name.                                                                                             MIDI OUT Device name is incorrect. Please use listed device name.

**Comment by raspy135** [comment]
Can you describe your environment such as OS?
What command line did you put? It seems like there are no MIDI devices on your computer.

**Comment by guilhermeollopes** [comment]
Eu uso o Windows 10. E ultilizo o loopMidi para criar as portas MIDI.
O cofigo que useri foi:
`python.exe .\serialmidi.py --serial_name=COM4 --midi_in_name="mnin" --midi_out_name="mnout"`
mnin e mnout foram os nomes que dei as portas no loop midi

**Comment by raspy135** [comment]
I don't understand the language you use so the answer will be just a guess.

When you do 
python.exe .\serialmidi.py --serial_name=COM4
And if "mmin" or "mnout" is not shown in the list, it means the MIDI loopback device is not recognized to the program.
I don't know why. Do you see those device names in your DAW?

**Comment by guilhermeollopes** [comment]
Yes, in my DAW the devices are recognized normally

**Comment by raspy135** [comment]
I'm not sure what the problem is, if the device is not listed when you do 
python.exe .\serialmidi.py --serial_name=COM4
Then it means Python doesn't recognize any MIDI devices. It could be drive issue, or Python installation issue.

**Comment by guilhermeollopes** [comment]
What would be the ideal version of python to run the code?

**Comment by raspy135** [comment]
Can you put the result of "python.exe .\serialmidi.py --serial_name=COM4 " command?
Also I want to see what's in device manager.
When I install loopMIDI the following screenshot shown.
![midi](https://github.com/raspy135/serialmidi/assets/63468646/0b3a4641-f56f-46f3-bae4-c7e46c3f2d96)

**Comment by guilhermeollopes** [comment]
I opened the device manager and there are some midi cables that I already deleted. Maybe it's something on the computer. I'll try to use it on another one and come back to tell you if it worked

**Comment by guilhermeollopes** [comment]
Test on another notebook and it worked normally, it's a problem with my notebook. But as I will be using it on the computer that is inside the pipe organ I am building, there is no problem, I believe that on his computer it will work normally.
